name: Update Hue Json Data

on:
    schedule:
        - cron: "0 */24 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  pip install requests

            - name: Run hue.py
              run: python ./utils/hue.py

            - name: Configure git
              run: |
                  git config --global user.name github-actions
                  git config --global user.email github-actions[bot]@users.noreply.github.com

            - name: Commit and push changes
              run: |
                  if git diff-index --quiet HEAD --; then
                    echo "No changes detected."
                  else
                    git add .
                    git commit -m "chore: update hue data"
                  fi
              continue-on-error: true

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  branch: main
                  github_token: ${{ secrets.GITHUB_TOKEN }}
